### ISSUE TITLE
Question: regarding the laravel-nuxt package requirement

### ISSUE THREAD

**Issue by timothymarois** [m2sd/nuxt-laravel-starter#11]
Hey Guys,

I noticed this has been worked on for a year or more, but only recently have created a release version. I 'm down to use a template to help Laravel and Nuxt work together, but I noticed, you'r composer requirement uses another package of yours called "laravel-nuxt", which makes me think this is bigger than just a skeleton template for both frameworks. Assuming you guys are committed to making this work long term, can you explain what the "laravel-nuxt" package does to make this template function? 

Looking very promising and cant wait to test it out!

**Comment by GautierDele** [comment]
Hello @timothymarois,
laravel-nuxt permit to link laravel to nuxt, this is fork from https://github.com/skyrpex/laravel-nuxt-js
We really want to push the package ahead but currently @mentAl-maZe and I are doing our best to maintain the package and adding new functionnality. Unfortunately we are both very busy.
