### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by pikelito** [m2sd/nuxt-laravel-starter#12]
clone repository, install dependencies and npm run dev, Listening: in http: // localhost: 3000 / app / and show server error

**Comment by mekontso** [comment]
Hello having same issue here. @pikelito did you solve it ?

**Comment by mekontso** [comment]
How to solve this.
Run this commands first:
-composer install
-npm install
then create the .env file
generate the app key with command: php artisan key:generate
then run
npm run dev

**Comment by GautierDele** [comment]
Hello,
Thanks @mekontso for the answer
Is this still a problem @pikelito ?
