### ISSUE TITLE
EventSource wrong MIME type

### ISSUE THREAD

**Issue by GautierDele** [m2sd/nuxt-laravel-starter#6]
Hello,

If we use this package and run npm update to update dependencies we get this new error:
`EventSource's response has a MIME type ("text/html") that is not "text/event-stream". Aborting the connection.`
This problem seems to be coming from axios because `npm update @nuxtjs/axios` is giving the error.
Something might have changed, did you get info on this @mentAl-maZe  ?

Gautier

**Comment by mentAl-maZe** [comment]
Solved in latest release
